### ISSUE TITLE
No GPU env cannot run the model

### ISSUE THREAD

**Issue by Janady** [notAI-tech/fastPunct#7]
I have try it on python 3.7 env without cuda. 

Succefully Downloaded to: /home/ubuntu/.fastPunct_en/params.pkl
2020-07-26 00:38:16.243790: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-07-26 00:38:16.243966: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-26 00:38:16.244079: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (VM-0-7-ubuntu): /proc/driver/nvidia/version does not exist
2020-07-26 00:38:16.244661: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-26 00:38:16.545005: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2394445000 Hz
2020-07-26 00:38:16.545635: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe014000b20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-26 00:38:16.545671: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda/lib/python3.7/site-packages/fastpunct/fastpunct.py", line 170, in __init__
    self.model.load_weights(weights_path)
  File "/home/ubuntu/miniconda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
...

**Comment by bedapudi6788** [comment]
> 2020-07-26 00:38:16.243790: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory

This might indicate a non-working tensorflow install on your machine. 

Can you check if you are able to use any other tensorflow based libraries. This module has no specific dependency on GPU. In fact, the docker image I provided is cpu-only.

**Comment by harikodali** [comment]
look like an issue with your tensorflow installation, this module doesn't require GPU, try a different version of tf or may be only
 tf-cpu
